### ISSUE TITLE
Curly Brace in configuration.py

### ISSUE THREAD

**Issue by NOMADEDCODER** [linuxserver/docker-netbox#36]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Program Run
## Current Behavior

Local Container keeps running but Netbox doesnt run
## Steps to Reproduce

1.Fresh install on unraid

## Docker logs

SyntaxError: unmatched '}'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 324)
spawned uWSGI worker 1 (pid: 341, cores: 1)
[uwsgi-daemons] spawning "/usr/bin/python3 ./manage.py rqworker" (uid: 99 gid: 100)
Traceback (most recent call last):
  File "/app/netbox/netbox/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 87, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 74, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/netbox/netbox/netbox/settings.py", line 55, in <module>
    configuration = importlib.import_module(config_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/netbox/netbox/netbox/configuration.py", line 246
    REMOTE_AUTH_DEFAULT_PERMISSIONS = REMOTE_AUTH_DEFAULT_PERMISSIONS}
                                                                     ^
SyntaxError: unmatched '}'
daemon "/usr/bin/python3 ./manage.py rqworker" (pid: 342) annihilated

**Comment by t46g** [comment]
Had the same problem today, with a fresh install on unraid.

**Comment by trollmehard** [comment]
I've still the same issue on unraid with a fresh install. I tried to set REMOTE_AUTH_DEFAULT_PERMISSIONS to "{" which didn't help. Is there any workaround? 

`*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 137)
spawned uWSGI worker 1 (pid: 145, cores: 1)
[uwsgi-daemons] spawning "/usr/bin/python3 ./manage.py rqworker" (uid: 99 gid: 100)
Traceback (most recent call last):
  File "/app/netbox/netbox/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 87, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 74, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/netbox/netbox/netbox/settings.py", line 55, in <module>
    configuration = importlib.import_module(config_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/netbox/netbox/netbox/configuration.py", line 246
    REMOTE_AUTH_DEFAULT_PERMISSIONS = {}}
                                        ^
SyntaxError: unmatched '}'
daemon "/usr/bin/python3 ./manage.py rqworker" (pid: 146) annihilated`

**Comment by ready-1** [comment]
Same issue on a fresh install.

**Comment by NathanWarrick** [comment]
I'm getting the same issue!!! This is so frustrating!!

**Comment by Qaezar** [comment]
Hi there ! 

I also had the same error and i maybe have a beginning of something :

In fact, the file configuration.py (in my case at least), do not update or keep the right info in it
So, i opened the unraid's terminal and gone to `/mnt/user/appdata/netbox`
There lies the configuration.py

Edited it and verified all the variables (you can remove the unneeded curly brace here)

In my case i had to fix redis TASKS & CACHING variables (host, pwd..) ; remove the curly brace and set :
`BASE_PATH = ''`
Plus correct some `false` into `False` and add `'` characters at the beginning and ending of the `REMOTE_AUTH_DEFAULT_GROUPS` variable

After that, restarted Netbox docker and bim, welcome WebUI

**BUT** i'm now in another problem, i can't login :/
The container doesn't seem to take in count the superuser id&pwd fields... so it's throwing an error about that :/

![image](https://user-images.githubusercontent.com/58505954/218255124-4bd73cd5-6ade-41a8-b4fa-16f186197314.png)

If someone find how to fix this, please let me now ;)
