### ISSUE TITLE
[BUG] apparently breaking changes with v4.0.0-ls195

### ISSUE THREAD

**Issue by ovizii** [linuxserver/docker-netbox#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I upgraded from v3.7.8-ls194 to v4.0.0-ls195. Netbox throws an error:

`s6-rc: warning: unable to start service init-netbox-config: command exited 1`

### Expected Behavior

Netbox should start

### Steps To Reproduce

Not sure what to say, upgraded from v3.7.8-ls194 to v4.0.0-ls195.

### Environment

```markdown
- OS:Debian Bookworm
- How docker service was installed: from docker's repo:  https://download.docker.com/linux/debian bookworm stable
```

### CPU architecture

x86-64

### Docker creation

```bash
services:

# https://docs.linuxserver.io/images/docker-netbox
# https://github.com/linuxserver/docker-netbox


  netbox:
    image: lscr.io/linuxserver/netbox:latest
    container_name: netbox
    hostname: netbox
    networks:
      netbox:
        ipv4_address: 192.168.192.102
      traefik_netbox:
      netbox_internal:
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
      - "SUPERUSER_EMAIL=me@dom.tld"
      - "SUPERUSER_PASSWORD=secret"
      - "ALLOWED_HOSTS=['netbox.int.dom.tld', 'localhost']"
      - "PREFER_IPV4 =true"
      - "DB_NAME=netbox"
      - "DB_USER=netbox"
      - "DB_PASSWORD=secret"
      - "DB_HOST=netbox-postgresql"
#      - DB_PORT=5432
      - "REDIS_HOST=netbox-redis"
#      - REDIS_PORT=6379
#      - REDIS_PASSWORD=
#      - REDIS_DB_TASK=
#      - REDIS_DB_CACHE=
#      - BASE_PATH= #optional
#      - REMOTE_AUTH_ENABLED= #optional
#      - REMOTE_AUTH_BACKEND= #optional
#      - REMOTE_AUTH_HEADER= #optional
#      - REMOTE_AUTH_AUTO_CREATE_USER= #optional
#      - REMOTE_AUTH_DEFAULT_GROUPS= #optional
#      - REMOTE_AUTH_DEFAULT_PERMISSIONS= #optional
    volumes:
      - ./netbox:/config
#    ports:
#      - 8000:8000
    restart: "no"
    cpus: 1
    mem_limit: 1G
    depends_on:
      netbox-postgresql:
        condition: service_healthy
      netbox-redis:
         condition: service_healthy
    labels:
      # enable Traefik
      - traefik.enable=true
      # Network
      - traefik.docker.network=traefik_netbox
      # Router
      - traefik.http.routers.netbox.tls=true
      - traefik.http.routers.netbox.entrypoints=websecure
      - traefik.http.routers.netbox.rule=Host(`netbox.int.dom.tld`)
      - traefik.http.routers.netbox.middlewares=secHeaders@file,localIPsOnly@file
      - traefik.http.routers.netbox.service=netbox
      # Service
      - traefik.http.services.netbox.loadbalancer.server.port=8000
      - traefik.http.services.netbox.loadbalancer.server.scheme=http
    healthcheck:
      test: nc -z localhost 8000 > /dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m00s
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

Operations to perform:
  Apply all migrations: account, auth, circuits, contenttypes, core, dcim, django_rq, extras, ipam, sessions, social_django, taggit, tenancy, users, virtualization, vpn, wireless
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/app/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/commands/shell.py", line 127, in handle
    exec(sys.stdin.read(), globals())
  File "<string>", line 7, in <module>
  File "/lsiopy/lib/python3.11/site-packages/django/db/models/manager.py", line 196, in __get__
    raise AttributeError(
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'users.User'
s6-rc: warning: unable to start service init-netbox-config: command exited 1
```

**Comment by thespad** [comment]
We'll have to take a look at the breaking changes in v4 and get the image updated

**Comment by thespad** [comment]
Please test the PR image from https://github.com/linuxserver/docker-netbox/pull/55 once it has completed building (it'll post the image tag as a comment in the PR).

**Comment by sjwk** [comment]
Thanks for the speedy fix, can confirm that the image in the PR works - at least as far as successfully starting up and logging in.     Will now start delving into it on my test container and see what's new.
